version: '3'

services:
  rest-backend:
    image: server:0.1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5500:5500"
#    depends_on:
#      - front
    environment:
      - SERVER_PORT= 5500
      - MY-PROPERTIES_FILE-WAY=logtest.txt